language: java

jdk:
 - openjdk8
 - oraclejdk8

branches:
only:
- master
before_script: # Perform commands
- cd seip2019
script:
 - mvn clean package

after_success:
- echo “Process terminated successfully”
