language: java

jdk:
 - openjdk8
 - oraclejdk8

branches:
only:
- master

sudo: required

before_install:
- sudo apt update

install:
- sudo apt install maven –y

before_script:
- cd project

script:
 - mvn clean package

after_success:
- echo “Process terminated successfully”
